era5_ref_table <- data.frame(variable = c("Time",
                              "Air temperature",
                              "Dewpoint temperature",
                              "Wind u-vector at 10m",
                              "Wind v-vector at 10m",
                              "Total precipitation",
                              "Snowfall",
                              "Surface level pressure",
                              "Downwelling shortwave radiation",
                              "Downwelling longwave radiation"
                              ),
                 era5 = c("time",
                          "2m_temperature",
                          "2m_dewpoint_temperature",
                          "10m_u_component_of_wind",
                          "10m_v_component_of_wind",
                          "total_precipitation",
                          "snowfall",
                          "surface_pressure",
                          "surface_solar_radiation_downwards",
                          "surface_thermal_radiation_downwards"
                          ),
                 nc = c("time",
                        "t2m",
                        "d2m",
                        "u10",
                        "v10",
                        "tp",
                        "sf",
                        "sp",
                        "ssrd",
                        "strd"
                        ),
                 ler = c("datetime",
                         "Air_Temperature_celsius",
                         "Dewpoint_Temperature_celsius",
                         "Ten_Meter_Uwind_vector_meterPerSecond",
                         "Ten_Meter_Vwind_vector_meterPerSecond",
                         "Precipitation_millimeterPerHour",
                         "Snowfall_millimeterPerHour",
                         "Surface_Level_Barometric_Pressure_pascal",
                         "Shortwave_Radiation_Downwelling_wattPerMeterSquared",
                         "Longwave_Radiation_Downwelling_wattPerMeterSquared"
                         ),
                 aeme = c("Date",
                          "MET_tmpair",
                          "MET_tmpdew",
                          "MET_wnduvu",
                          "MET_wnduvv",
                          "MET_pprain",
                          "MET_ppsnow",
                          "MET_prsttn",
                          "MET_radswd",
                          "MET_radlwd"),
                 nc_unit = c("Date",
                             "K",
                             "K",
                             "m s**1",
                             "m s**1",
                             "m",
                             "m",
                             "Pa",
                             "J m**-2",
                             "J m**-2"
                             ),
                 agg_fun = c("mean",
                             "mean",
                             "mean",
                             "mean",
                             "mean",
                             "sum",
                             "sum",
                             "mean",
                             "mean",
                             "mean")
                 )

usethis::use_data(era5_ref_table, overwrite = TRUE)
