#' Run GR model
#'
#' @param inputs list; of inputs generated by `make_GR_inputs()`.
#' @param param vector; of parameters. Usually generated from `calib_GR()`.
#' @param warmup vector; index of `inputs$data` to be used as a warmup period
#' for the model.
#' @param run_index vector; index of `inputs$data` to be used for running the
#' GR model.
#' @inheritParams airGR::CreateRunOptions
#'
#'
#' @return list of GR model output.
#' @export

run_GR <- function(inputs, param, warmup = NULL, run_index,
                   IniStates = NULL, IniResLevels = NULL) {
  rlang::check_installed("airGR", reason = "to run GR models.")

  RunOptions <- make_RunOptions(inputs = inputs, warmup = warmup,
                                run_index = run_index,
                                IniStates = IniStates,
                                IniResLevels = IniResLevels)

  out <- inputs$FUN_MOD(InputsModel = inputs$InputsModel,
                        RunOptions = RunOptions, Param = param)
  out$catchment_area <- inputs$catchment_area
  out
}
